import type { Metadata } from "next";
import { Poppins as PrimaryFont } from "next/font/google";
import "./globals.css";

const primaryFont = PrimaryFont({ subsets: ["latin"], weight: ["300", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={primaryFont.className}>{children}</body>
    </html>
  );
}
